name: Bug
description: Something isn't working
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Platform, OS version, app version.
    validations:
      required: true
